### ISSUE TITLE
Renaming weapons breaks attacks

### ISSUE THREAD

**Issue by jsavko** [Ward-Ceyssens/foundryvtt-warhammer-40k-10th#3]
**Describe the bug**
Naming a weapon/ adding attack details  prevents it from opening a dialog
**To Reproduce**

Create new weapon on model actor sheet
Edit weapon with any stats
Try to use weapon

**Expected behavior**
Dialog doesn't open and console errors

**Screenshots**
![image](https://github.com/Ward-Ceyssens/foundryvtt-warhammer-40k-10th/assets/192591/36236b3d-e1d7-45dc-b846-fd4b43660033)

**Desktop (please complete the following information):**
 - Foundry Version: 11.315

**Comment by Ward-Ceyssens** [comment]
I'm sorry but I'm unable to reproduce this issue.

This error dialog occurs late in the targeting workflow and should only fail if selected tokens are in range but do not possess the required weapon. So I think you may have accidentally selected another token while editing this sheet.

**Comment by jsavko** [comment]
I can assure you I wasn't selected the wrong token, but if the error is because of range, then it may be worth updating the error message to indicate it's a range error
