### ISSUE TITLE
Add a compendium

### ISSUE THREAD

**Issue by rorp24** [Ward-Ceyssens/foundryvtt-warhammer-40k-10th#5]
**Is your feature request related to a problem? Please describe.**
I wanted to fix by myself [this issue](https://github.com/Ward-Ceyssens/foundryvtt-warhammer-40k-10th/issues/4
) so I started re creating the missing items but it's a long process. Since you seems to have the datas, I think having a compendium would allow us to have the ability to quickfix this kind of bug.

**Comment by Ward-Ceyssens** [comment]
The system (intentionally) does not contain any unit data, the roster importer reads this data from the roster file. While a compendium would be useful I believe providing unit data may get me in legal trouble with Games Workshop so I will not be doing that.
